---
Name: iqconstantcontact
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - IQnection\ConstantContact\SiteConfig\SiteConfig
---
Only:
  classexists: 'IQnection\FormPage\FormPage'
---
IQnection\FormPage\FormPage:
  extensions:
    - IQnection\ConstantContact\FormPage\FormPage
IQnection\FormPage\Model\FormPageSubmission:
  extensions:
    - IQnection\ConstantContact\FormPage\Model\FormPageSubmission